name: Call a reusable workflow

on:
  workflow_dispatch:
    inputs:
      username:
        description: '收件箱展示的来件人名字'
        required: true
        default: '大表哥'

jobs:
  # call-workflow:
  #   uses: octo-org/example-repo/.github/workflows/workflow-A.yml@v1

  call-workflow-passing-data:
    uses: qzsiniong/github-actions-demo/.github/workflows/child.yml@main
    with:
      username: ${{ inputs.username }}
    secrets:
      token: ${{ secrets.TOKEN }}